

trigger:
  batch: true
  branches:
    include:
    - main
pr:
  branches:
    include:
    - '*'  # Builds will run for pull requests

resources:
- repo: self

name: $(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
stages:
  - stage: Build
    jobs:
      - job: Temp_name_attempt
        pool: 
         vmimage: ubuntu-latest
        steps:
            - checkout: self
              submodules: true
              lfs: true

  - stage: Deploy
    jobs:
      - deployment: Deploy_job_deployment_temp
        environment: $(env)
        pool: 
         vmimage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current

              - task: HelmInstaller@0
                inputs:
                  helmVersion: '3'
                  installKubectl: true

              - task: HelmDeploy@0
                inputs:
                  command: 'upgrade'
                  chartType: 'FilePath'
                  chartPath: '$(Pipeline.Workspace)/generic-chart/'
                  valueFile: '$(Pipeline.Workspace)/generic-chart/values-deploy.yaml'
                  overrideValues: image.repository=$(REPO)/aivum/client,image.tag=$(Build.BuildNumber)
                  useClusterAdmin: true
